"""Detached finalizer: wait for the Gemini robustness orchestrator to finish, then
run the deterministic offline pipeline end to end and commit/push. Each step's
exit code is logged to logs/finalize.log; it stops at the first failure and
never commits if validation or the secret scan fails."""

from __future__ import annotations

from datetime import datetime, timezone
import json
import os
from pathlib import Path
import subprocess
import sys
import time

ROOT = Path(__file__).resolve().parents[1]
PY = sys.executable
LOG = ROOT / "logs" / "finalize.log"


def log(msg: str) -> None:
    with LOG.open("a", encoding="utf-8") as fh:
        fh.write(f"{datetime.now(timezone.utc).isoformat(timespec='seconds')} {msg}\n")


def run(args: list[str]) -> int:
    env = {**os.environ, "PYTHONIOENCODING": "utf-8"}
    with LOG.open("a", encoding="utf-8") as fh:
        rc = subprocess.call(args, cwd=ROOT, stdout=fh, stderr=subprocess.STDOUT, env=env)
    log(f"rc={rc} :: {' '.join(args[-3:])}")
    return rc


def main() -> None:
    log("finalizer start; waiting for 'orchestrator done family=google_gemini'")
    orch = ROOT / "logs" / "orchestrator.log"
    while "orchestrator done family=google_gemini" not in orch.read_text(encoding="utf-8"):
        time.sleep(120)
    steps = [
        [PY, "scripts/audit_core_dataset.py", "robust_cue_location"],
        [PY, "scripts/run_analysis.py", "robust_cue_location"],
        [PY, "scripts/make_figures_tables.py", "core"],
        [PY, "scripts/render_manuscript.py"],
        [PY, "scripts/validate_final.py"],
        [PY, "scripts/build_reports.py"],
    ]
    for step in steps:
        if run(step) != 0:
            log("STOP: step failed; nothing committed")
            return
    val = json.loads((ROOT / "artifacts" / "final_validation.json").read_text(encoding="utf-8"))
    if not val.get("all_passed"):
        log("STOP: final validation did not pass; nothing committed")
        return
    run(["git", "add", "-A", "data", "artifacts", "outputs", "manuscript", "submission", "scripts", "docs", "roadmap.md", "README.md", "references"])
    from dotenv import dotenv_values
    secrets = [v for v in dotenv_values(ROOT / ".env").values() if v]
    staged = subprocess.run(["git", "diff", "--cached", "--name-only"], cwd=ROOT, capture_output=True, text=True).stdout.split()
    if any(any(s.encode() in (ROOT / n).read_bytes() for s in secrets) for n in staged if (ROOT / n).is_file()):
        log("STOP: secret detected in staged files; nothing committed")
        return
    msg = ("phase4: cue-location robustness, final figures/tables, manuscript, validation and submission package\n\n"
           "Generated by scripts/finalize_pipeline.py after the frozen robustness stages completed.\n\n"
           "Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>")
    if run(["git", "commit", "-q", "-m", msg]) == 0:
        run(["git", "push", "origin", "main"])
    log("finalizer done")


if __name__ == "__main__":
    main()
